# Shiny Dynamic UI

创建动态用户界面有三种关键技术:

*使用update更新函数族修改输入控件的参数*

*使用tabsetPanel()有条件地显示和隐藏部分用户界面*

*使用uiOutput()和renderUI()用代码生成用户界面的选定部分*

## Updating inputs

```{r}
library(shiny)

ui <- fluidPage(
  numericInput("n","Simulations",10),
  actionButton("simulate","Simulate")
)

server <- function(input, output, session) {
  observeEvent(input$n, {
    label<-paste0("Simulate",input$n,"times")
    updateActionButton(inputId = "simulate",label=label)
  })
}

```
 
```{r}
library(shiny)

ui <- fluidPage(
  selectInput("dataset","Choose a dataset",c("pressure","cars")),
  selectInput("column","Choose column",character(0)),
  verbatimTextOutput("summary")
)

server <- function(input, output, session) {
  # freezeReactiveValue(input,"column")
  dataset<-reactive(get(input$dataset,"package:datasets"))
  
  observeEvent(input$dataset,{
    updateSelectInput(inputId = "column",choices = names(dataset()))
  })
  output$summary<-renderPrint({
    summary(dataset()[[input$column]])
  })
}

```

## Dynamic visibility

```{r}
library(shiny)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput("controller","Show",choices = paste0("panel",1:3))
    ),
    mainPanel(
      tabsetPanel(
        id="switcher",
        type="hidden",
        tabPanelBody("panel1","Panel 1 content"),
        tabPanelBody("panel2","Panel 2 content"),
        tabPanelBody("panel3","Panel 3 content")
      )
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$controller,{
    updateTabsetPanel(inputId = "switcher",selected=input$controller)
  })
}

```

```{r}
library(shiny)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput("dist","Distribution",
                  choices=c("normal","uniform","exponential")),
      numericInput("n","Number of samples",value=100),
      parameter_tabs<-tabsetPanel(
        id="params",
        type="hidden",
        tabPanel("normal",
                 numericInput("mean","mean",value=1),
                 numericInput("sd","standard deviation",min=0,value=1)),
        tabPanel("uniform",
                 numericInput("min","min",value=0),
                 numericInput("max","max",value=1)),
        tabPanel("exponential",
                 numericInput("rate","rate",value=1,min=0))
      )
    ),
    mainPanel(
      plotOutput("hist")
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$dist,{
    updateTabsetPanel(inputId="params",selected = input$dist)
  })
  sample<-reactive({
    switch(input$dist,
           normal=rnorm(input$n,input$mean,input$sd),
           uniform=runif(input$n,input$min,input$max),
           exponential=rexp(input$n,input $ rate))
  })
  output$hist<-renderPlot(hist(sample()),res=96)
}

```

```{r}
library(shiny)

ui <- fluidPage(
  tabsetPanel(
    id="wizard",
    type="hidden",
    tabPanel("page_1",
             "Welcome!",
             actionButton("page_12","next")),
    tabPanel("page_2","Only one page to go",
             actionButton("page_21","prev"),
             actionButton("page_23","next")),
    tabPanel("page_3","You're done!",
             actionButton("page_32","prev"))
  )
)

server <- function(input, output, session) {
  switch_page<-function(i){
    updateTabsetPanel(inputId="wizard",selected=paste0("page_",i))
  }
  observeEvent(input$page_12,switch_page(2))
  observeEvent(input$page_21,switch_page(1))
  observeEvent(input$page_23,switch_page(3))
  observeEvent(input$page_32,switch_page(2))
  
}

```

## Creating UI with code

```{r}
library(shiny)

ui <- fluidPage(
  textInput("label","label"),
  selectInput("type","type",c("slider","numeric")),
  uiOutput("numeric")
)
server <- function(input, output, session) {
  output$numeric<-renderUI({
    #value<-isolate(input$dynamic)
    if(input$type=="slider"){
      sliderInput("dynamic",input$label,value=0,min=0,max=10)
    }else{
      numericInput("dynamic",input$label,value=0,min=0,max=10)
    }
  })
}

```

```{r}
library(purrr)
library(shiny)

ui <- fluidPage(
  numericInput("n", "Number of colours", value = 5, min = 1),
  uiOutput("col"),
  textOutput("palette")
)


server <- function(input, output, session) {
  col_names <- reactive(paste0("col", seq_len(input$n)))
  
  output$col <- renderUI({
    map(col_names(), ~ textInput(.x, NULL))
  })
  
  output$palette <- renderText({
    map_chr(col_names(), ~ input[[.x]] %||% "")
  })
}

```


```{r}
library(shiny)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      numericInput("n", "Number of colours", value = 5, min = 1),
      uiOutput("col"),
    ),
    mainPanel(
      plotOutput("plot")  
    )
  )
)

server <- function(input, output, session) {
  col_names <- reactive(paste0("col", seq_len(input$n)))
  
  output$col <- renderUI({
    map(col_names(), ~ textInput(.x, NULL, value = isolate(input[[.x]])))
  })
  
  output$plot <- renderPlot({
    cols <- map_chr(col_names(), ~ input[[.x]] %||% "")
    # convert empty inputs to transparent
    cols[cols == ""] <- NA
    
    barplot(
      rep(1, length(cols)), 
      col = cols,
      space = 0, 
      axes = FALSE
    )
  }, res = 96)
}

```
